export const districtElectoralAreas = {
  // Western Region
  JOMORO: [
    "BENYIN",
    "ELUBO WEST",
    "TIKOBO NO. 2",
    "SEWODADZEM",
    "TIKOBO NO. 1",
    "ADUBRIM",
    "AKROPONG",
    "MUNTUKWA",
    "AYAWORA/EKOKONU",
    "KWESIKROM",
    "NEW ADIEMBRA",
    "NEW AIYINASE",
  ],
  ELLEMBELE: [
    "ADUBRIM",
    "AKROPONG",
    "MUNTUKWA",
    "AYAWORA/EKOKONU",
    "KWESIKROM",
    "NEW ADIEMBRA",
    "NEW AIYINASE",
    "AIYINASI",
    "AWIEBO",
    "DOMINASE",
  ],
  "NZEMA EAST": ["AXIM", "NSEIN", "KIKAM", "GWIRA BANSO", "BAMIANKO", "AIYINASI", "AWIEBO", "DOMINASE", "AKANGO"],
  "AHANTA WEST": [
    "AGONA NKWANTA",
    "APOWA",
    "ABURA",
    "AKATAKYI",
    "EWUSIEJOE",
    "HOTOPO",
    "KEJABIL",
    "NEW AKWIDAA",
    "PRINCES TOWN",
  ],
  SHAMA: ["SHAMA", "INCHABAN", "ABOADZE", "ABUESI", "ASSORKO ESSAMAN", "BEPOSO", "KOMFUEKU", "NYANOM", "SUPOM DUNKWA"],

  // Central Region
  "KOMENDA/EDINA/EGUAFO/ABIREM": ["KOMENDA", "ELMINA", "EGUAFO", "ABIREM", "KISSI", "ANKAFUL", "ESSIAM"],
  "CAPE COAST": ["ABURA", "PEDU", "ASENADZE", "BAKANO", "NKANFOA", "AMANFUL", "NTSIN"],
  "ABURA/ASEBU/KWAMANKESE": ["ABURA DUNKWA", "ASEBU", "KWAMANKESE", "MOREE", "ABAKRAMPA", "NYAMEBEKYERE"],
  MFANTSEMAN: ["SALTPOND", "ANOMABO", "YAMORANSA", "KORMANTSE", "BIRIWA", "NKWANTA"],
  EKUMFI: ["ESSUEHYIA", "OTUAM", "EYISAM", "SRAFA", "EKUMPOANO", "IMMUNA"],

  // Greater Accra Region
  "GA SOUTH": ["WEIJA", "GBAWE", "BORTIANOR", "NGLESHIE AMANFRO", "DOMEABRA", "OBOM"],
  "GA WEST": ["AMASAMAN", "POKUASE", "OFANKOR", "AYIKAI DOBLO", "KOTOKU", "MAYERA"],
  "GA CENTRAL": ["ANYAA", "SOWUTUOM", "AWOSHIE", "SANTA MARIA", "KWASHIEMAN", "ABLEKUMA"],
  LEDZOKUKU: ["TESHIE", "NUNGUA", "BAATSONAA", "SAKUMONO", "SPINTEX", "MANET"],
  KROWOR: ["NUNGUA ZONGO", "NUNGUA TRADITIONAL", "LASHIBI", "SAKUMONO ESTATES", "TEMA NEWTOWN"],

  // Volta Region
  KETA: ["KETA CENTRAL", "ANLO-AFIADENYIGBA", "ANLOGA", "WOE", "TEGBI", "VODZA"],
  ANLOGA: ["ANLOGA", "WHUTI", "SROGBOE", "KEDZIKOPE", "ATSIAVI", "ANYANUI"],
  "KETU SOUTH": ["AFLAO", "DENU", "AGBOZUME", "KLIKOR", "NOGOKPO", "WUDOABA"],
  "KETU NORTH": ["DZODZE", "PENYI", "AFIFE", "WETA", "TADZEWU", "EHI"],
  "AKATSI SOUTH": ["AKATSI", "AVENORPEME", "GEFIA", "WUTE", "AGBEDRAFOR", "ATIDZIVE"],

  // Eastern Region
  ASUOGYAMAN: ["ATIMPOKU", "AKWAMUFIE", "BOSO", "GYAKITI", "MPAKADAN", "SENCHI"],
  "LOWER MANYA KROBO": ["ODUMASE", "AGOMANYA", "KPONG", "AKUSE", "MANYA KPONGUNOR", "YOKUNOR"],
  "UPPER MANYA KROBO": ["ASESEWA", "SEKESUA", "AKATENG", "ANYABONI", "SUTSU", "BREPAW"],
  "YILO KROBO": ["SOMANYA", "NKURAKAN", "OBAWALE", "HUHUNYA", "OTERKPOLU", "SRA"],
  "AKUAPEM NORTH": ["AKROPONG", "LARTEH", "MAMFE", "ADAWSO", "ABIRIW", "AWUKUGUA"],
  "KWAEBIBIREM": ["APENKWA - ASUOM", "ATOBRISO", "KOKA/MINTA BOMENG", "KWAMANG", "AKAWANI"],

  // Ashanti Region
  "ADANSI SOUTH": ["NEW EDUBIASE", "ATOBIASE", "ASOKWA", "FUMSO", "AKAPORISO", "ANHWIASO"],
  AKROFUOM: ["AKROFUOM", "AMPUNYASE", "GRUMESA", "ADAMSO", "BETENASE", "OBUASI"],
  "ADANSI NORTH": ["FOMENA", "DOMPOASE", "AKROKERRI", "BODWESANGO", "AYAASE", "FUMSO"],
  "ADANSI ASOKWA": ["ASOKWA", "HWIREMOASE", "ANHWIASO", "BODWESANGO", "FUMSO", "DOMPOASE"],
  "OBUASI MUNICIPAL": ["OBUASI CENTRAL", "KUNKA", "GAUSU", "TUTUKA", "BOGOBIRI", "SANSO"],

  // Western North Region
  AOWIN: ["ENCHI", "JEMA", "DADIESO", "BOINSO", "SEWUM", "YAKASI"],
  SUAMAN: ["DADIESO", "KARLO", "SUAMAN", "OBENGKROM", "ANTOKROM", "BODI"],
  "BIBIANI-ANHWIASO-BEKWAI": ["BIBIANI", "ANHWIASO", "BEKWAI", "CHIRANO", "SUBIRI", "TANOSO"],
  "SEFWI WIAWSO": ["WIAWSO", "ASAWINSO", "AHOKWA", "BOSOMOISO", "SEFWI ASEMPANEYE", "SEFWI WIAWSO"],
  "SEFWI AKONTOMBRA": ["AKONTOMBRA", "NSAWORA", "TANOSO", "ESSAM", "ADABOKROM", "SEFWI BEKWAI"],

  // Ahafo Region
  "ASUNAFO SOUTH": ["KUKUOM", "SANKORE", "KWAPONG", "ASAREKROM", "NOBERKAW", "PESIKROM"],
  "ASUNAFO NORTH": ["GOASO", "MIMA", "FAWOHOYEDEN", "AYOMSO", "ASUMURA", "KASAPIN"],
  "ASUTIFI SOUTH": ["HWIDIEM", "ACHERENSUA", "NKASEIM", "DADIESOABA", "MEHAME", "KWAKU NYOMA"],
  "ASUTIFI NORTH": ["KENYASI NO.1", "KENYASI NO.2", "NTOTROSO", "WAMAHINSO", "GYEDU", "GAMBIA NO.2"],
  "TANO SOUTH": ["BECHEM", "TECHIMANTIA", "DERMA", "BROSANKRO", "DWOMO", "ADAA"],

  // Bono Region
  "SUNYANI MUNICIPAL": ["SUNYANI CENTRAL", "ABESIM", "NKWABENG", "YAWHIMA", "ATRONIE", "NEW DORMAA"],
  "SUNYANI WEST MUNICIPAL": ["ODUMASE", "CHIRAA", "FIAPRE", "NSOATRE", "ADENTIA", "BOFOURKROM"],
  "DORMAA WEST": ["NKRANKWANTA", "KRAKROM", "YAAKROM", "KWAKUANYA", "DIABAA", "NSESRESO"],
  "DORMAA CENTRAL MUNICIPAL": ["DORMAA AHENKRO", "WAMFIE", "ABOABO NO.4", "KOSANE", "NSUHIA", "ANTWIRIFO"],
  "DORMAA EAST": ["WAMANAFO", "AKONTANIM", "KYEREMASU", "WAMFIE", "NKRANKWANTA", "DORMAA AKWAMU"],

  // Bono East Region
  "TECHIMAN MUNICIPAL": ["TECHIMAN CENTRAL", "HANSUA", "TRAA", "TANOSO", "AWOROWA", "NKWAESO"],
  "KINTAMPO NORTH": ["KINTAMPO", "BABATOKUMA", "DAWADAWA", "GULUMPE", "NEW LONGORO", "BUSUAMA"],
  "KINTAMPO SOUTH": ["JEMA", "AMOMA", "ANYIMA", "KRABONSO", "APESIKA", "PRAMPOSO"],
  "NKORANZA NORTH": ["BUSUNYA", "KRANKA", "DROMANKESE", "BOANA", "YEFRI", "BONTE"],
  "NKORANZA SOUTH MUNICIPAL": ["NKORANZA", "AKUMSA DOMASE", "DOTOBAA", "BRAHOHO", "SESIMAN", "DONKRO NKWANTA"],

  // Oti Region
  JASIKAN: ["JASIKAN", "OKADJAKROM", "BODADA", "TETEMAN", "NEW BAIKA", "KOTONSU"],
  BIAKOYE: ["NKONYA AHENKRO", "NKONYA WURUPONG", "APESOKUBI", "TAPA AMANYA", "BOWIRI AMANFROM", "KWAMEKROM"],
  KADJEBI: ["KADJEBI", "DODI PAPASE", "DODI ASATO", "AHAMANSU", "DODO PEPESU", "WAWASO"],
  "KRACHI EAST": ["DAMBAI", "GRUBI", "KATANGA", "AYERUMU", "MOTORWAY", "TOKUROANO"],
  "KRACHI WEST": ["KETE KRACHI", "OSRAMANI", "GYEASAYO", "NTEWUSAE", "BEPOSO", "KAPENTE"],

  // Northern Region
  KPANDAI: ["KPANDAI", "KATIEJELI", "LONTO", "JAMBUAI", "NKANCHINA", "KABONWULE"],
  "NANUMBA NORTH": ["BIMBILLA", "DAKPAM", "JUO", "PUSUGA", "CHAMBA", "LUNGNI"],
  "NANUMBA SOUTH": ["WULENSI", "NAKPAYILI", "LUNGNI", "PUDUA", "KPASSA", "TINJA"],
  ZABZUGU: ["ZABZUGU", "YELIZOLI", "RAJIA", "TASUNDO", "KUKPALIGU", "SABARE"],
  "TATALE/SANGULI": ["TATALE", "SANGULI", "NAHUYILI", "KPALBA", "YAPEI", "BICHACHABI"],

  // Savannah Region
  BOLE: ["BOLE", "BAMBOI", "TINGA", "MALUWE", "MANDARI", "CHACHE"],
  "SAWLA-TUNA-KALBA": ["SAWLA", "TUNA", "KALBA", "GINDABOUR", "NYANGE", "KUNFUSI"],
  "WEST GONJA": ["DAMONGO", "BUSUNU", "LARABANGA", "MOLE", "DABOYA", "MANKUMA"],
  "NORTH GONJA": ["DABOYA", "LINGBINSI", "MANKARIGU", "YAGBON", "KUSAWGU", "TIDROPE"],
  "CENTRAL GONJA": ["BUIPE", "YAPEI", "SANKPALA", "MPAHA", "KUSAWGU", "FUFULSO"],

  // North East Region
  "WEST MAMPRUSI": ["WALEWALE", "WULUGU", "YAMA", "JANGA", "KPASENKPE", "DABOYA"],
  "MAMPRUGU MOAGDURI": ["YAGABA", "KUBORI", "LOAGRI", "ZANGUN", "KPATORIGU", "GORIBA"],
  "EAST MAMPRUSI": ["GAMBAGA", "NALERIGU", "SAKOGU", "LANGBINSI", "GBINTIRI", "NAGBOO"],
  "BUNKPURUGU-NAKPANDURI": ["BUNKPURUGU", "NAKPANDURI", "NASUAN", "BINDE", "YUNYOO", "NAMONG"],
  "YUNYOO-NASUAN": ["YUNYOO", "NASUAN", "KPALGBINI", "TONG", "GBINGBALANCHET", "KINKANG"],
  CHEREPONI: ["CHEREPONI", "WENCHIKI", "TAMBI", "UGANDO", "ADARI", "KPENCHI"],

  // Upper East Region
  "BUILSA SOUTH": ["FUMBISI", "KANJAGA", "CHUCHULIGA", "UWASI", "GBEDEMA", "DONINGA"],
  "BUILSA NORTH MUNICIPAL": ["SANDEMA", "WIAGA", "KADEMA", "CHUCHULIGA", "SINIENSI", "BACHONSA"],
  "KASSENA NANKANA MUNICIPAL": ["NAVRONGO CENTRAL", "KOLOGO", "PUNGU", "VUNANIA", "NAKONG", "MANYORO"],
  "KASSENA NANKANA WEST": ["PAGA", "CHIANA", "KAYORO", "KATIU", "SIRIGU", "MIRIGU"],
  BONGO: ["BONGO", "SOE", "ZORKO", "BALUNGU", "NAMOO", "BOKO"],

  // Upper West Region
  "WA MUNICIPAL": ["WA CENTRAL", "BUSA", "KPERISI", "BOLI", "CHARIA", "KPONGU"],
  "WA WEST": ["WECHIAU", "DORIMON", "VIERI", "GURUNGU", "NYOLI", "TANINA"],
  "WA EAST": ["FUNSI", "BULENGA", "KUNDUNGU", "GORIPIE", "DUPARI", "YAALA"],
  "NADOWLI/KALEO": ["NADOWLI", "KALEO", "SOMBO", "JANG", "SANKANA", "TAKPO"],
  "DAFFIAMA-BUSSIE-ISSA": ["ISSA", "DAFFIAMA", "BUSSIE", "FIAN", "OWLO", "TABIESI"],
}
