-- SQL script to insert three people with comprehensive data into the census database

-- Insert Person 1: Kwame Asante (Male, from Ashanti Region)
INSERT INTO people (
  first_name,
  last_name,
  middle_name,
  gender,
  date_of_birth,
  place_of_birth,
  citizenship,
  hometown,
  region,
  district,
  electoral_area,
  marital_status,
  number_of_children,
  residential_address,
  gps_address,
  home_type,
  family_clan,
  clan_head,
  contact_number,
  father_name,
  mother_name,
  id_type,
  id_number,
  occupation,
  place_of_work,
  education_level,
  school_name,
  photo_url
) VALUES (
  'Kwame',
  'Asante',
  'Osei',
  'male',
  '1985-03-15',
  'Kumasi',
  'Ghanaian',
  'Kumasi',
  'Ashanti',
  'KUMASI METROPOLITAN',
  'ADUM',
  'married',
  2,
  'House No. 45, Adum Street, Kumasi',
  'AK-123-4567',
  'owned',
  'Asona',
  'Nana Kwaku Asona',
  '+233244567890',
  'Osei Kwame',
  'Akosua Manu',
  'national_id',
  'GHA-123456789-0',
  'Teacher',
  'Kumasi Senior High School',
  'Bachelor''s Degree',
  'University of Cape Coast',
  'https://example.com/photos/kwame_asante.jpg'
);

-- Insert Person 2: Akosua Mensah (Female, from Greater Accra Region)
INSERT INTO people (
  first_name,
  last_name,
  middle_name,
  gender,
  date_of_birth,
  place_of_birth,
  citizenship,
  hometown,
  region,
  district,
  electoral_area,
  marital_status,
  number_of_children,
  residential_address,
  gps_address,
  home_type,
  landlord_name,
  landlord_contact,
  family_clan,
  clan_head,
  contact_number,
  father_name,
  mother_name,
  id_type,
  id_number,
  occupation,
  place_of_work,
  education_level,
  school_name,
  photo_url
) VALUES (
  'Akosua',
  'Mensah',
  'Ama',
  'female',
  '1992-07-22',
  'Accra',
  'Ghanaian',
  'Tema',
  'Greater Accra',
  'TEMA METROPOLITAN',
  'TEMA NEWTOWN',
  'single',
  0,
  'Apt 12B, Community 8, Tema',
  'GA-789-1234',
  'rented',
  'Mr. Joseph Tetteh',
  '+233201234567',
  'Aduana',
  'Nana Yaw Aduana',
  '+233277654321',
  'Kwame Mensah',
  'Ama Serwaa',
  'drivers_license',
  'DL-987654321',
  'Software Developer',
  'Tech Solutions Ghana Ltd',
  'Master''s Degree',
  'University of Ghana',
  'https://example.com/photos/akosua_mensah.jpg'
);

-- Insert Person 3: Kofi Boateng (Male, from Western Region)
INSERT INTO people (
  first_name,
  last_name,
  gender,
  date_of_birth,
  place_of_birth,
  citizenship,
  hometown,
  region,
  district,
  electoral_area,
  marital_status,
  number_of_children,
  residential_address,
  gps_address,
  home_type,
  family_clan,
  clan_head,
  contact_number,
  father_name,
  mother_name,
  id_type,
  id_number,
  occupation,
  place_of_work,
  education_level,
  school_name,
  photo_url
) VALUES (
  'Kofi',
  'Boateng',
  'male',
  '1978-11-08',
  'Takoradi',
  'Ghanaian',
  'Sekondi',
  'Western',
  'SEKONDI-TAKORADI METROPOLITAN',
  'SEKONDI',
  'divorced',
  1,
  'Block 5, Sekondi Estate',
  'WR-456-7890',
  'family',
  'Bretuo',
  'Nana Kofi Bretuo',
  '+233208765432',
  'Yaw Boateng',
  'Efua Adjei',
  'national_id',
  'GHA-987654321-1',
  'Fisherman',
  'Sekondi Fishing Harbor',
  'Junior High School',
  'Sekondi Methodist JHS',
  'https://example.com/photos/kofi_boateng.jpg'
);

-- Verify the insertions
SELECT 
  id,
  name,
  gender,
  date_of_birth,
  region,
  district,
  family_clan,
  occupation,
  created_at
FROM people 
WHERE first_name IN ('Kwame', 'Akosua', 'Kofi')
ORDER BY created_at DESC;